In 202
cimplec/sim-c pull request #330
Opened 2020-10-25 12:44 UTC by lucasace

Added the following math constants to simc
```
C Name->SIMC Name
M_PI ->pi
M_E -> e
INFINITY -> inf
NAN ->nan
```

Test CODE:
```simc
MAIN
	print(inf)
	print(e)
	print(pi)
	print(nan)
	print(-inf)
END_MAIN
```

2020-10-25 20:15 UTC, frankhart2018 requested changes
Looks good, I just wanted to point out that keeping the constants all in upper case (like in C) will be better otherwise someone might feel they are just variables.

2020-10-26 03:38 UTC, lucasace commented
How about PI,E,inf,NaN

2020-10-26 11:22 UTC, frankhart2018 commented
Yeah this looks good too @lucasace. Have you made the changes?

2020-10-26 13:17 UTC, lucasace commented
> Yeah this looks good too @lucasace. Have you made the changes?

Yes, I have made the changes

2020-10-26 13:18 UTC, lucasace commented on simc/lexical_analyzer.py
> +    if value in ["PI","E","inf","NaN"]:
Yes I have made the changes

2020-10-26 13:18 UTC, frankhart2018 approved these changes
Looks good, merging this. Thanks for your contribution @lucasace. Closes #202.

2020-10-26 13:19 UTC, merged