Added boolean value support.
cimplec/sim-c pull request #388
Opened 2020-12-10 16:27 UTC by prit108

Fixes #355 .
Use boolean constants **true** and **false** to assign bool variables. These are mapped to **int** **1** and **0** in C code respectively.
Note : **true** and **false** are keywords now and cannot be used a identifier names any longer.
Example:
![BooleanSupport](https://user-images.githubusercontent.com/63956555/101799762-8c1c4a80-3b32-11eb-96de-8b2d7286934d.png)

2020-12-10 16:58 UTC, Math-O5 commented
@prit108 Well done, I'm checking your code. But to be merged, the code should follow the CONTRIBUTING.md file instructions. In your case, you miss name branch as **` in-355`**

2020-12-10 17:16 UTC, Math-O5 commented
@prit108 The solution is in discussion. Do you think you can solve this using bool of C instead of int and set to zero and one? Yours solution works fine, but it's losing memory in saving as int instead of boolean.

2020-12-11 13:18 UTC, frankhart2018 commented
> @Math-O5 Okay will work on doing that. Just to confirm you intend to use stdbool.h for the job right..

Yeah

2020-12-13 19:35 UTC, Math-O5 requested changes
Add review: change requested

2020-12-16 14:20 UTC, Math-O5 commented
@prit108 Any update? To be merged, just resolve conflict with branch master.

2020-12-16 14:31 UTC, prit108 commented
> @prit108 Any update? To be merged, just resolve conflict with branch master.

@Math-O5 I am working on it... was busy for a few days, will finish soon.

2020-12-16 16:15 UTC, Math-O5 commented
@prit108 Ok, no worry, I just warn you in case you were participating of KwoC 2020, that end today, I think so.

2020-12-16 16:17 UTC, frankhart2018 commented
No @Math-O5 it ends on Jan 4th. But on 18th they have mid evals which requires them to have 1 merged commit.

2020-12-19 17:08 UTC, prit108 commented
@Math-O5 
Added the requested bool datatype from stdbool.h. Kindly review.

2020-12-19 17:17 UTC, frankhart2018 requested changes
1) Line 225-230 is redundant in keyword_identifer function - lexical_analyzer.py
2) Line 60 does not need parantheses in while inside expression() - simc_parser.py
3) Please provide test simC code so that we can verify it.

2020-12-19 18:26 UTC, prit108 commented
@frankhart2018 update the changes requested. Please find attached the a sample test. I would have uploaded the file but Github is not supporting the file format.
#####
MAIN
var x = true
var d = 9
print(d)
if(x) {
	print("Voila!!")
}
END_MAIN
#####
![Screenshot from 2020-12-19 23-52-35](https://user-images.githubusercontent.com/63956555/102696610-9c7ca580-4255-11eb-8aef-7b57561b8740.png)

2020-12-20 11:53 UTC, frankhart2018 requested changes
1) The redundancy in line 219-225 still exists in keyword_identifier - lexical_analyzer.py
2) Also your branch name is not proper check CONTRIBUTING.md.

2020-12-20 12:31 UTC, closed without merging